Use sink directly for tableRow with comments
mojohaus/taglist-maven-plugin pull request #167
Opened 2024-10-11 20:38 UTC by slawekjaranowski

fix #165

2024-10-11 21:19 UTC, michael-o requested changes

2024-10-11 21:19 UTC, michael-o commented on src/main/java/org/codehaus/mojo/taglist/TaglistReportRenderer.java
> +        sink.tableCell_();
Here you can cheat: https://github.com/apache/maven-reporting-impl/blob/a4d9b2ff9c031aa270b5366410c39bad2b0eb0ad/src/main/java/org/apache/maven/reporting/AbstractMavenReportRenderer.java#L199-L201

2024-10-12 12:20 UTC, michael-o approved these changes

2024-10-12 19:51 UTC, merged

2024-10-12 20:40 UTC, garydgregory commented
Nice, and and thank you 😊

2024-10-12 20:41 UTC, michael-o commented
> Nice, and and thank you 😊

No no problem.